export const calendarMeal1 = [
  {
    id: 1,
    day: "Thứ 2",
    type: "monday",
    mainMeal: "Thịt kho khổ qua",
    subMeal: "Rau muống xào tỏi",
    soup: "Canh rau muống vắt chanh",
  },
  {
    id: 2,
    day: "Thứ 3",
    type: "tuesday",
    mainMeal: "Cá trê chiên giòn mắm gừng",
    subMeal: "Gỏi xoài",
    soup: "Canh khoai mỡ nấu tôm",
  },
  {
    id: 3,
    day: "Thứ 4",
    type: "wednesday",
    mainMeal: "Cốt lếch áp chảo",
    subMeal: "Su su xào tỏi",
    soup: "Canh cải xanh nấu thịt",
  },
  {
    id: 4,
    day: "Thứ 5",
    type: "thursday",
    mainMeal: "Đậu hủ nhồi thịt sốt cà",
    subMeal: "Cải thìa xào tỏi",
    soup: "Canh bắp cải nấu thịt",
  },
  {
    id: 5,
    day: "Thứ 6",
    type: "friday",
    mainMeal: "Chả cá kho cà",
    subMeal: "Cải ngọt luộc",
    soup: "Canh rau má nấu thịt",
  },
];
